### ISSUE TITLE
zinit log should have an option top quit after printing the logs

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/zinit#49] opened 2023-02-06 07:32 UTC
Currently `zinit log` seems to follow the log and I have to quit by typing `Ctr-C`.

**Comment by muhamadazmy** [comment] 2023-03-16 15:27
It's by design actually. Also the logs are read over a Unix socket connection from zinit ring buffer directly which is always attached (filled) from active process logs. Hence there is actually no way u can tell u reached the end of the logs because there is no end.

**Comment by muhamadazmy** [comment] 2023-03-17 12:06
Fixed in https://github.com/threefoldtech/zinit/releases/tag/v0.2.11

Now you can provide `-s` flag (for snapshot) to the `zinit log` command to only print a snapshot of the current logs buffer.

```bash
zinit log -s
```
or 
```bash
zinit log -s <service-name>
```

**Closed by muhamadazmy** 2023-03-17 12:06 UTC
Labels: type_feature
